package com.careerconnect.enums;

public enum JobCategoryEnum {
    IT,
    SOFTWARE_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    WEB_DEVELOPMENT,
    SALES,
    MARKETING,
    ACCOUNTING,
    GRAPHIC_DESIGN,
    CONTENT_WRITING,
    MEDICAL,
    TEACHING,
    ENGINEERING,
    PRODUCTION,
    LOGISTICS,
    HOSPITALITY,
    REAL_ESTATE,
    LAW,
    FINANCE,
    HUMAN_RESOURCES,
    CUSTOMER_SERVICE,
    ADMINISTRATION,
    MANAGEMENT,
    OTHER
}
